# System settings
data_file: feff_Ti_OS_CN_OCN_NNRS_MOOD_spec_vasp_grid_20230714_0139.csv
trials: 100
timeout: 10
verbose: true
max_epoch: 1500
batch_size: 1024

gradient_reversal: true # if true, `alpha_flat_step` and `alpha_limit` must be specified.
alpha_flat_step: 739 # Alpha will reach to `alpha_limit` and stay constant after `alpha_flat_step` ecpochs.
alpha_limit: 0.7172
decoder_activation: Softplus
dis_beta: 1.1
dis_dropout_rate: 0.056
dis_noise: 0.56
gen_beta: 1.1

# Report Parameters
output_name: report
top_n: 20
gpu: true
# plot_job: job_64
plot_residual: false
n_sampling: 1000

# Network Structure
n_aux: 5
nstyle: 6
ae_form: FC
dim_in: 256
dim_out: 256 # if ae_form==normal, dim_out is always set to 256
n_layers: 5 # FC only
FC_discriminator_layers: 3 # used only if use_cnn_discriminator==false
use_cnn_discriminator: false

# Training Parameters
dropout_rate: 0.04
sch_factor: 0.1
sch_patience: 100

lr_base: 0.001
lr_ratio_Corr: 10
lr_ratio_Mutual: 1
lr_ratio_Reconn: 10
lr_ratio_Smooth: 1
lr_ratio_dis: 1
lr_ratio_gen: 10
optimizer_name: AdamW
spec_noise: 0.02
use_flex_spec_target: true
weight_decay: 0.01
kendall_force_balance: true
epoch_stop_smooth: 1500
